name: Add changelog label to merged PR
on:
  repository_dispatch:
    types:
      - hmm
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: echo payload
        run: echo ${{ github.event.client_payload }}
      - name: Apply label
        uses: actions/github-script@0.4.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.addLabels({
              issue_number: 3,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['Changelog Entry: Pending']
            });
